# see documentation, e.g.
# - https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata
# - https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
# - https://www.python.org/dev/peps/pep-0621/

[build-system]
requires = ["setuptools>=64.0.0", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
authors = [{ name = "Dani Bodor", email = "dani.bodor@kb.nl" }]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]
dependencies = ["requests"]
description = "parse a natural language query to a cql query for delpher"
keywords = [""]
license = { file = "LICENSE" }
name = "nl2query"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.13"
version = "0.1.0"

[project.optional-dependencies]
dev = [
    "build",           # build is not only used in publishing (below), but also in the template's test suite
    "bump-my-version",
    "coverage [toml]",
    "pytest",
    "pytest-cov",
    "ruff==0.15.*",
    "mypy",
    "types-requests",
]
docs = []
publishing = ["build", "twine", "wheel"]

[project.urls]
Repository = "https://github.com/DaniBodor/nl2query"
Issues = "https://github.com/DaniBodor/nl2query/issues"
Changelog = "https://github.com/DaniBodor/nl2query/CHANGELOG.md"
ReadTheDocs = "https://nl2query.readthedocs.io"

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
exclude = "build/.*"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["src/nl2query"]
command_line = "-m pytest"

[tool.bumpversion]
current_version = "0.1.0"

[[tool.bumpversion.files]]
filename = "src/nl2query/__init__.py"

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "CITATION.cff"

[[tool.bumpversion.files]]
filename = "docs/conf.py"
