line-length = 100
output-format = "concise"
extend-exclude = ["docs"]

[lint]
select = ["ALL"]
ignore = [
    "ANN204", # Missing return type annotation for special (dunder) method
    "FIX",    # Disallows TODO/FIXME/XXX comments
    "TD",     # Forces addition information on TODOs
    "B028",   # No explicit `stacklevel` keyword argument found in warning
    # No docstrings required in the following cases
    "D100", # Missing module docstring
    "D104", # Missing public package docstring
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in `__init__`
]
pydocstyle.convention = "google"
unfixable = [
    "F401",   # unused imports (should not disappear while editing)
    "B905",   # zip-without-explicit-strict
    "T201",   # print-statements
    "RUF100", # remove unused noqa (preferable to control when this happens?)
]
extend-safe-fixes = [
    "D415",   # First line should end with a period, question mark, or exclamation point
    "TC",     # Format type checking only imports
    "EM",     # Exception message variables
    "RUF013", # Implicit Optional
    "B006",   # Mutable default argument
]

[lint.per-file-ignores]
# Tests can ignore a few extra rules
"tests/**.py" = [
    "ANN201", # Missing return type annotation for public function
    "PT011",  # Missing `match` parameter in `pytest.raises()`
    "S101",   # Use of assert is detected
]

[lint.isort]
known-first-party = ["nl2query"]
force-single-line = true
